/**
 * Tablk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Group {
  id: string;
  sessionId: string;
  type: Group.TypeEnum;
  memberIds: Array<string>;
}
export namespace Group {
  export type TypeEnum = "Main" | "Sub";
  export const TypeEnum = {
    Main: "Main" as TypeEnum,
    Sub: "Sub" as TypeEnum
  };
}
