/**
 * Tablk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Member {
  id: number;
  sessionId: number;
  userId: number;
  imageUrl: string;
  /**
   * typeがGameMasterの時には存在しない
   */
  defaultCharacterId?: number;
  color: string;
  type: Member.TypeEnum;
}
export namespace Member {
  export type TypeEnum = "Player" | "GameMaster";
  export const TypeEnum = {
    Player: "Player" as TypeEnum,
    GameMaster: "GameMaster" as TypeEnum
  };
}
