/**
 * Tablk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MessageOptions } from "./messageOptions";

export interface Message {
  id: string;
  type: Message.TypeEnum;
  message: string;
  createdAt: string;
  options: MessageOptions;
  memberId: string;
  /**
   * Act のみ存在する
   */
  roleAs?: string;
}
export namespace Message {
  export type TypeEnum = "Narration" | "Act" | "Message";
  export const TypeEnum = {
    Narration: "Narration" as TypeEnum,
    Act: "Act" as TypeEnum,
    Message: "Message" as TypeEnum
  };
}
