/**
 * Tablk
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Character } from "./character";
import { Member } from "./member";
import { Note } from "./note";
import { Session } from "./session";
import { User } from "./user";

export interface SessionsResponse {
  sessions: { [key: string]: Session };
  members: { [key: string]: Member };
  characters: { [key: string]: Character };
  users: { [key: string]: User };
  notes: { [key: string]: Note };
}
